import {
  LayoutDashboard,
  Brain,
  BarChart3,
  GraduationCap,
  Settings,
  Users,
  UsersRound,
  ClipboardList,
  UserCog,
  SlidersHorizontal,
  FileBarChart,
  History,
  BookOpen,
  CalendarClock,
  LineChart,
  MessageSquareText,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  LayoutDashboard,
  Brain,
  BarChart3,
  GraduationCap,
  Settings,
  Users,
  UsersRound,
  ClipboardList,
  UserCog,
  SlidersHorizontal,
  FileBarChart,
  History,
  BookOpen,
  CalendarClock,
  LineChart,
  MessageSquareText,
};
